In [28]:
import polars as pl
import pandas as pd

## Загрузка 2.0

In [23]:
pddf = pd.read_excel('df/data_marker_1_2020.xlsx',
                     sheet_name="Результаты поиска",
                     dtype={'Реестровый номер публикации': str,
                            'ИНН заказчика': str,
                            'ИНН поставщика': str})

In [30]:
df = pl.from_pandas(pddf)

In [39]:
dforg = df

In [40]:
df = df.drop(['Банковское \\ казначейское сопровождение', 'Источник финансирования', 'Ссылка на источник'])

In [68]:
for i in range(4, 16):
    new = pd.read_excel(f'df/data_marker_{i}_2020.xlsx',
                        sheet_name="Результаты поиска",
                        dtype={'Реестровый номер публикации': str,
                                'ИНН заказчика': str,
                                'ИНН поставщика': str})
    newpl = pl.from_pandas(new)
    newpl = newpl.drop(['Банковское \\ казначейское сопровождение', 'Источник финансирования', 'Ссылка на источник'])
    print(i, new.shape, newpl.shape)
    
    newpl = newpl.with_columns(pl.col('Идентификационный код закупки').cast(pl.String))
    newpl = newpl.with_columns(pl.col('Дата  окончания проведения торгов').cast(pl.Datetime('ns')))


    df = pl.concat([df, newpl])

4 (808171, 31) (808171, 28)
5 (752787, 31) (752787, 28)
6 (763198, 31) (763198, 28)
7 (803087, 31) (803087, 28)
8 (648139, 31) (648139, 28)
9 (882757, 31) (882757, 28)
10 (814251, 31) (814251, 28)
11 (858080, 31) (858080, 28)
12 (897081, 31) (897081, 28)
13 (785894, 31) (785894, 28)
14 (960160, 31) (960160, 28)
15 (953149, 31) (953149, 28)

In [69]:
loaded_df = df

In [71]:
df.shape

(12406878, 28)

2 (1083717, 31) (1083717, 28) 

3 (927562, 31) (927562, 28)

### Обработка

In [74]:
data = df.rename({'Стоимость \n(руб.) Заказчик' : 'Стоимость(руб.) Заказчик',
                  'Дата \nокончания приема заявок / Дата планового окончания исполнения контракта / Плановая дата публикации лота по ППГ':'Дата окончания приема заявок / Дата планового окончания исполнения контракта / Плановая дата публикации лота по ППГ',
                  'Дата начала подачи заявок/Дата начала исполнения контракта / Дата публикации ППГ' : 'Дата начала подачи заявок / Дата начала исполнения контракта / Дата публикации ППГ',
                  'Дата  окончания проведения торгов' : 'Дата окончания проведения торгов',
                  'Стоимость\n(руб.) Поставщик' : 'Стоимость(руб.) Поставщик'})

In [77]:
data.columns

['Уровень',
 'Заказчик',
 'ИНН заказчика',
 'Стоимость(руб.) Заказчик',
 'Реестровый номер публикации',
 'Идентификационный код закупки',
 'Сфера деятельности',
 'Наименование публикации',
 'Регион поставки',
 'Город поставки',
 'Дата публикации',
 'Дата окончания приема заявок / Дата планового окончания исполнения контракта / Плановая дата публикации лота по ППГ',
 'Дата начала подачи заявок / Дата начала исполнения контракта / Дата публикации ППГ',
 'Дата окончания проведения торгов',
 'Поставщик',
 'ИНН поставщика',
 'Победитель',
 'Статус допуска',
 'Стоимость(руб.) Поставщик',
 'Снижение на торгах,%',
 'Форма публикации',
 'Тип торгов',
 'Торговая площадка',
 'Электронные торги',
 'Обеспечение заявки (руб.)',
 'Обеспечение заявки, %',
 'Обеспечение контракта (руб.)',
 'Обеспечение контракта, %']

In [78]:
data = data.drop(['Наименование публикации', 'Стоимость(руб.) Поставщик', 'Торговая площадка', 'Электронные торги'])

In [79]:
data.head(2)

shape: (2, 24)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Уровень ┆ Заказчик   ┆ ИНН       ┆ Стоимость ┆ … ┆ Обеспечен ┆ Обеспечен ┆ Обеспечен ┆ Обеспечен │
│ ---     ┆ ---        ┆ заказчика ┆ (руб.)    ┆   ┆ ие заявки ┆ ие        ┆ ие        ┆ ие контра │
│ i64     ┆ str        ┆ ---       ┆ Заказчик  ┆   ┆ (руб.)    ┆ заявки, % ┆ контракта ┆ кта, %    │
│         ┆            ┆ str       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ (руб.)    ┆ ---       │
│         ┆            ┆           ┆ f64       ┆   ┆ f64       ┆ f64       ┆ ---       ┆ f64       │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆ f64       ┆           │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1       ┆ УФССП      ┆ 732703326 ┆ 123475.0  ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│         ┆ РОССИИ ПО  ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆ УЛЬЯНОВСКО ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆ Й ОБ…      ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1       ┆ УФССП      ┆ 732703326 ┆ 3150.0    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│         ┆ РОССИИ ПО  ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆ УЛЬЯНОВСКО ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆ Й ОБ…      ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

Оставляем только те строки, где есть ИНН заказчика и поставщика.

In [80]:
data = data.filter(pl.col("ИНН поставщика").is_not_null() & pl.col("ИНН заказчика").is_not_null())
data.shape

(538277, 24)

Оставляем только те строки, где известно снижение на торгах

In [81]:
data = data.filter(pl.col("Снижение на торгах,%").is_not_null())
data.shape

(457531, 24)

Уберем нереалистичные значения в ставках в Снижение на торгах,%

In [82]:
data = data.filter((pl.col('Снижение на торгах,%')>=-100))
data.shape

(457028, 24)

Теперь работаем с датами

In [83]:
data = data.filter(pl.col('Дата публикации').is_not_null() & 
                    pl.col('Дата окончания приема заявок / Дата планового окончания исполнения контракта / Плановая дата публикации лота по ППГ').is_not_null() & 
                    pl.col('Дата начала подачи заявок / Дата начала исполнения контракта / Дата публикации ППГ').is_not_null() & 
                    pl.col('Дата окончания проведения торгов').is_not_null())
data.shape

(410446, 24)

Убираем дупликаты

In [84]:
data = data.unique()
data.shape

(404863, 24)

Смотрим, по каким данным определять уникальность закупки

In [85]:
data.filter(pl.col('Реестровый номер публикации')!=pl.lit("")).shape

(404863, 24)

In [94]:
data.unique(['ИНН заказчика', 'Реестровый номер публикации']).shape

(199241, 25)

In [95]:
data.unique(['ИНН заказчика', 
             'Реестровый номер публикации', 
             'Дата публикации',
             'Дата окончания приема заявок / Дата планового окончания исполнения контракта / Плановая дата публикации лота по ППГ',
             'Дата начала подачи заявок / Дата начала исполнения контракта / Дата публикации ППГ',
             'Дата окончания проведения торгов']).shape

(199248, 25)

Отбираем тендеры, где известен победитель

In [86]:
data.select(pl.all().null_count())

shape: (1, 24)
┌─────────┬──────────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Уровень ┆ Заказчик ┆ ИНН        ┆ Стоимость( ┆ … ┆ Обеспечен ┆ Обеспечен ┆ Обеспечен ┆ Обеспечен │
│ ---     ┆ ---      ┆ заказчика  ┆ руб.)      ┆   ┆ ие заявки ┆ ие        ┆ ие        ┆ ие контра │
│ u32     ┆ u32      ┆ ---        ┆ Заказчик   ┆   ┆ (руб.)    ┆ заявки, % ┆ контракта ┆ кта, %    │
│         ┆          ┆ u32        ┆ ---        ┆   ┆ ---       ┆ ---       ┆ (руб.)    ┆ ---       │
│         ┆          ┆            ┆ u32        ┆   ┆ u32       ┆ u32       ┆ ---       ┆ u32       │
│         ┆          ┆            ┆            ┆   ┆           ┆           ┆ u32       ┆           │
╞═════════╪══════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0       ┆ 0        ┆ 0          ┆ 246547     ┆ … ┆ 380755    ┆ 391940    ┆ 390810    ┆ 374778    │
└─────────┴──────────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [87]:
data = data.with_columns(pl.when(pl.col('Победитель')==pl.lit('Победитель')).then(1).otherwise(0).alias('Есть победитель'))
data.shape

(404863, 25)

In [96]:
data_group = data.group_by(['Реестровый номер публикации']).agg(pl.col('Есть победитель').sum().alias('Num winner'))
data_group.shape

(198379, 2)

In [97]:
data_new = data.join(data_group,
                     how='left',
                     on=['Реестровый номер публикации'])
data_new.shape

(404863, 26)

In [99]:
data = data_new.filter(pl.col('Num winner')>=1)
data.shape

(109775, 26)

In [100]:
data = data.drop(["Есть победитель", "Num winner"])

Добавляем реестр недобросовестных поставщиков

In [105]:
notrust = pl.read_json('notrust_list/res.json')

In [106]:
notrust = notrust.rename({'suplier_name':'Поставщик', 'suplier_inn':'ИНН поставщика', 'no_trust_now':'РНП сейчас', 'no_trust_before':'РНП ранее'})

In [107]:
data = data.join(other=notrust.select(['ИНН поставщика', 'РНП сейчас', 'РНП ранее']), on='ИНН поставщика', how='left')
data = data.with_columns(pl.col('РНП сейчас').fill_null(0), pl.col('РНП ранее').fill_null(0))

In [110]:
data.filter(pl.col('РНП ранее')==1).shape

(419, 26)

Записываем результат

In [111]:
data.shape

(109900, 26)

In [112]:
data.write_excel( dtype_formats={pl.Date: "yyyy-mm-dd"})

--------

In [4]:
import polars as pl

In [21]:
df = pl.read_excel(source='/Users/renatavaliullina/Desktop/rec b2b/data_final(2020-2025)/data_final_res(2020-2025)_revenue_no_null.xlsx')
df = df.select(['ИНН заказчика', 'Стоимость(руб.) Заказчик', 'Реестровый номер публикации'])
df = df.rename({'ИНН заказчика':'inn', 'Стоимость(руб.) Заказчик':'price', 'Реестровый номер публикации':'num'})
df = df.with_columns(pl.col('price').floor().cast(pl.Int64).alias('floor'), pl.col('price').ceil().cast(pl.Int64).alias('ceil'))
df = df.unique().sort('inn')
#df = df.to_pandas()

In [43]:
import re

s = "\n    \n        \n        \n            15 %\n        \n    \n"
num = re.search(r'(\d+)\s*%', s)  
num.group(1)

'15'

In [63]:
s = "\n    \n        \n            24 000,00 ₽\n            \n                (20 %)\n            \n        \n        \n    \n"
s.split()

['24', '000,00', '₽', '(20', '%)']

------------------

In [2]:
import polars as pl

In [3]:
df = pl.read_excel('correct_data/correct_data_2020.xlsx')
df.head(2)

shape: (2, 26)
┌─────────┬────────────┬────────────┬────────────┬───┬────────────┬───────────┬────────┬───────────┐
│ Уровень ┆ Заказчик   ┆ ИНН        ┆ Стоимость( ┆ … ┆ Обеспечени ┆ Обеспечен ┆ РНП    ┆ РНП ранее │
│ ---     ┆ ---        ┆ заказчика  ┆ руб.)      ┆   ┆ е          ┆ ие контра ┆ сейчас ┆ ---       │
│ i64     ┆ str        ┆ ---        ┆ Заказчик   ┆   ┆ контракта  ┆ кта, %    ┆ ---    ┆ i64       │
│         ┆            ┆ str        ┆ ---        ┆   ┆ (руб.)     ┆ ---       ┆ i64    ┆           │
│         ┆            ┆            ┆ f64        ┆   ┆ ---        ┆ f64       ┆        ┆           │
│         ┆            ┆            ┆            ┆   ┆ f64        ┆           ┆        ┆           │
╞═════════╪════════════╪════════════╪════════════╪═══╪════════════╪═══════════╪════════╪═══════════╡
│ 2       ┆ ГБУЗ АО    ┆ 3018005693 ┆ 49120.0    ┆ … ┆ null       ┆ 0.05      ┆ 0      ┆ 0         │
│         ┆ "ГКБ №3"   ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
│ 1       ┆ ФГБУ       ┆ 7706433263 ┆ 420000.0   ┆ … ┆ null       ┆ null      ┆ 0      ┆ 0         │
│         ┆ "ВИМС"     ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
└─────────┴────────────┴────────────┴────────────┴───┴────────────┴───────────┴────────┴───────────┘

In [10]:
df.filter(pl.col('ИНН заказчика')=='0274157821').filter(pl.col('Реестровый номер публикации')=='0801200000220000066').head(12)

shape: (2, 26)
┌─────────┬────────────┬────────────┬────────────┬───┬────────────┬───────────┬────────┬───────────┐
│ Уровень ┆ Заказчик   ┆ ИНН        ┆ Стоимость( ┆ … ┆ Обеспечени ┆ Обеспечен ┆ РНП    ┆ РНП ранее │
│ ---     ┆ ---        ┆ заказчика  ┆ руб.)      ┆   ┆ е          ┆ ие контра ┆ сейчас ┆ ---       │
│ i64     ┆ str        ┆ ---        ┆ Заказчик   ┆   ┆ контракта  ┆ кта, %    ┆ ---    ┆ i64       │
│         ┆            ┆ str        ┆ ---        ┆   ┆ (руб.)     ┆ ---       ┆ i64    ┆           │
│         ┆            ┆            ┆ f64        ┆   ┆ ---        ┆ f64       ┆        ┆           │
│         ┆            ┆            ┆            ┆   ┆ f64        ┆           ┆        ┆           │
╞═════════╪════════════╪════════════╪════════════╪═══╪════════════╪═══════════╪════════╪═══════════╡
│ 2       ┆ ГКУ ТЕХОБЕ ┆ 0274157821 ┆ 374867.36  ┆ … ┆ 37486.74   ┆ 0.1       ┆ 0      ┆ 0         │
│         ┆ СПЕЧЕНИЕ   ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
│         ┆ МЗ РБ      ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
│ 2       ┆ ГКУ ТЕХОБЕ ┆ 0274157821 ┆ 374867.36  ┆ … ┆ 37486.74   ┆ 0.1       ┆ 0      ┆ 0         │
│         ┆ СПЕЧЕНИЕ   ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
│         ┆ МЗ РБ      ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
└─────────┴────────────┴────────────┴────────────┴───┴────────────┴───────────┴────────┴───────────┘

In [2]:
import pandas as pd

In [27]:
pl.from_pandas(t)

shape: (3, 31)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Уровень ┆ Заказчик   ┆ ИНН       ┆ Стоимость ┆ … ┆ Обеспечен ┆ Банковско ┆ Источник  ┆ Ссылка на │
│ ---     ┆ ---        ┆ заказчика ┆ (руб.)    ┆   ┆ ие контра ┆ е \ казна ┆ финансиро ┆ источник  │
│ i64     ┆ str        ┆ ---       ┆ Заказчик  ┆   ┆ кта, %    ┆ чейское   ┆ вания     ┆ ---       │
│         ┆            ┆ str       ┆ ---       ┆   ┆ ---       ┆ сопр…     ┆ ---       ┆ str       │
│         ┆            ┆           ┆ f64       ┆   ┆ f64       ┆ ---       ┆ str       ┆           │
│         ┆            ┆           ┆           ┆   ┆           ┆ str       ┆           ┆           │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1       ┆ ГКУ ТЕХОБЕ ┆ 027415782 ┆ 374867.36 ┆ … ┆ null      ┆ Неизвестн ┆ Бюджет    ┆ Госзакупк │
│         ┆ СПЕЧЕНИЕ   ┆ 1         ┆           ┆   ┆           ┆ о         ┆ Республик ┆ и         │
│         ┆ МЗ РБ      ┆           ┆           ┆   ┆           ┆           ┆ и Башкорт ┆ 44ФЗ/94ФЗ │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆ остан     ┆           │
│ 2       ┆ ГКУ ТЕХОБЕ ┆ 027415782 ┆ 374867.36 ┆ … ┆ 0.1       ┆ Неизвестн ┆ null      ┆ Госзакупк │
│         ┆ СПЕЧЕНИЕ   ┆ 1         ┆           ┆   ┆           ┆ о         ┆           ┆ и         │
│         ┆ МЗ РБ      ┆           ┆           ┆   ┆           ┆           ┆           ┆ 44ФЗ/94ФЗ │
│ 2       ┆ ГКУ ТЕХОБЕ ┆ 027415782 ┆ 374867.36 ┆ … ┆ 0.1       ┆ Неизвестн ┆ null      ┆ Госзакупк │
│         ┆ СПЕЧЕНИЕ   ┆ 1         ┆           ┆   ┆           ┆ о         ┆           ┆ и         │
│         ┆ МЗ РБ      ┆           ┆           ┆   ┆           ┆           ┆           ┆ 44ФЗ/94ФЗ │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [26]:
t = pddf.loc[pddf['ИНН заказчика']=='0274157821'].loc[chunks['Стоимость \n(руб.) Заказчик']==374867.36]
t

,Уровень,Заказчик,ИНН заказчика,Стоимость \n(руб.) Заказчик,Реестровый номер публикации,Идентификационный код закупки,Сфера деятельности,Наименование публикации,Регион поставки,Город поставки,...,Тип торгов,Торговая площадка,Электронные торги,Обеспечение заявки (руб.),"Обеспечение заявки, %",Обеспечение контракта (руб.),"Обеспечение контракта, %",Банковское \ казначейское сопровождение,Источник финансирования,Ссылка на источник
40461,1,ГКУ ТЕХОБЕСПЕЧЕНИЕ МЗ РБ,0274157821,374867.36,0801200000220000066,20-20274157821027401001-0191-001-2120-323,Неизвестно,Поставка лекарственного(-ых) препарата(-ов) дл...,Республика Башкортостан,Уфа,...,Аукцион электронный,ЭТС,Неизвестно,3748.67,NaN,37486.74,NaN,Неизвестно,Бюджет Республики Башкортостан,Госзакупки 44ФЗ/94ФЗ
40462,2,ГКУ ТЕХОБЕСПЕЧЕНИЕ МЗ РБ,0274157821,374867.36,0801200000220000066,20-20274157821027401001-0191-001-2120-323,Неизвестно,Поставка лекарственного(-ых) препарата(-ов) дл...,Республика Башкортостан,Уфа,...,NaN,NaN,Неизвестно,3748.67,0.01,37486.74,0.1,Неизвестно,NaN,Госзакупки 44ФЗ/94ФЗ
40463,2,ГКУ ТЕХОБЕСПЕЧЕНИЕ МЗ РБ,0274157821,374867.36,0801200000220000066,20-20274157821027401001-0191-001-2120-323,Неизвестно,Поставка лекарственного(-ых) препарата(-ов) дл...,Республика Башкортостан,Уфа,...,NaN,NaN,Неизвестно,3748.67,0.01,37486.74,0.1,Неизвестно,NaN,Госзакупки 44ФЗ/94ФЗ

In [21]:
chunks.dtypes

Уровень                                                                                                                           int64
Заказчик                                                                                                                         object
ИНН заказчика                                                                                                                   float64
Стоимость \n(руб.) Заказчик                                                                                                     float64
Реестровый номер публикации                                                                                                      object
Идентификационный код закупки                                                                                                    object
Сфера деятельности                                                                                                               object
Наименование публикации                                                                                                          object
Регион поставки                                                                                                                  object
Город поставки                                                                                                                   object
Дата публикации                                                                                                          datetime64[ns]
Дата \nокончания приема заявок / Дата планового окончания исполнения контракта / Плановая дата публикации лота по ППГ    datetime64[ns]
Дата начала подачи заявок/Дата начала исполнения контракта / Дата публикации ППГ                                         datetime64[ns]
Дата  окончания проведения торгов                                                                                        datetime64[ns]
Поставщик                                                                                                                        object
ИНН поставщика                                                                                                                  float64
Победитель                                                                                                                       object
Статус допуска                                                                                                                   object
Стоимость\n(руб.) Поставщик                                                                                                     float64
Снижение на торгах,%                                                                                                            float64
Форма публикации                                                                                                                 object
Тип торгов                                                                                                                       object
Торговая площадка                                                                                                                object
Электронные торги                                                                                                                object
Обеспечение заявки (руб.)                                                                                                       float64
Обеспечение заявки, %                                                                                                           float64
Обеспечение контракта (руб.)                                                                                                    float64
Обеспечение контракта, %                                                                                                        float64
Банковское \ казначейское сопровождение                                                                                          object
Источник финансирования                                                                                                          object
Ссылка на источник                                                                                                               object
dtype: object