In [1]:
import polars as pl

In [2]:
df2020 = pl.read_excel(source='data/data_final_res(2020-2025).xlsx')
df2015 = pl.read_excel(source='data/data_final_res(2015-2020).xlsx')

In [4]:
df2020.head(2)

shape: (2, 22)
┌─────────┬─────────────┬─────────────┬─────────────┬───┬────────────┬────────┬────────┬───────────┐
│ Уровень ┆ Заказчик    ┆ ИНН         ┆ Стоимость(р ┆ … ┆ Форма      ┆ Тип    ┆ РНП    ┆ РНП ранее │
│ ---     ┆ ---         ┆ заказчика   ┆ уб.)        ┆   ┆ публикации ┆ торгов ┆ сейчас ┆ ---       │
│ i64     ┆ str         ┆ ---         ┆ Заказчик    ┆   ┆ ---        ┆ ---    ┆ ---    ┆ i64       │
│         ┆             ┆ i64         ┆ ---         ┆   ┆ str        ┆ str    ┆ i64    ┆           │
│         ┆             ┆             ┆ f64         ┆   ┆            ┆        ┆        ┆           │
╞═════════╪═════════════╪═════════════╪═════════════╪═══╪════════════╪════════╪════════╪═══════════╡
│ 2       ┆ АДМИНИСТРАЦ ┆ 4505003804  ┆ 99875.0     ┆ … ┆ Торговая   ┆ null   ┆ 0      ┆ 0         │
│         ┆ ИЯ ВАРГАШИН ┆             ┆             ┆   ┆ процедура  ┆        ┆        ┆           │
│         ┆ СКОГО РА…   ┆             ┆             ┆   ┆            ┆        ┆        ┆           │
│ 2       ┆ ГБОУ ШКОЛА  ┆ 7816165190  ┆ 47237.32    ┆ … ┆ Торговая   ┆ null   ┆ 0      ┆ 0         │
│         ┆ № 292 ФРУНЗ ┆             ┆             ┆   ┆ процедура  ┆        ┆        ┆           │
│         ┆ ЕНСКОГО …   ┆             ┆             ┆   ┆            ┆        ┆        ┆           │
└─────────┴─────────────┴─────────────┴─────────────┴───┴────────────┴────────┴────────┴───────────┘

In [25]:
inn2020 = df2020.select(pl.col('ИНН поставщика').unique())#.to_numpy().reshape(-1)
inn2015 = df2015.select(pl.col('ИНН поставщика').unique())#.to_numpy().reshape(-1)

In [29]:
inn = pl.concat([inn2020, inn2015]).select(pl.col('ИНН поставщика').unique())
inn

shape: (88_845, 1)
┌────────────────┐
│ ИНН поставщика │
│ ---            │
│ i64            │
╞════════════════╡
│ 6106196        │
│ 21350362       │
│ 100603804      │
│ 101010245      │
│ 101980148      │
│ …              │
│ 990102784250   │
│ 990103466758   │
│ 990103778740   │
│ 990116504915   │
│ 990199065793   │
└────────────────┘

In [34]:
inn.write_csv()

'ИНН поставщика\n6106196\n21350362\n100603804\n101010245\n101980148\n103007142\n104010814\n104012018\n104013340\n105003062\n105004524\n105015580\n105021223\n105036533\n105040160\n105045986\n105052567\n105052990\n105056025\n105057325\n105058819\n105060293\n105060310\n105060504\n105061297\n105064266\n105064876\n105065069\n105065622\n105065862\n105066055\n105070781\n105071560\n105071827\n105073006\n105073285\n105073969\n105075003\n105075677\n105076430\n105077681\n105078822\n105079311\n105079368\n105080902\n106009229\n107013299\n107017409\n107019685\n107021677\n107021758\n107021814\n107023018\n107025495\n107026121\n107026298\n107027164\n107027407\n107029309\n107031259\n107031570\n107033217\n107033721\n107035180\n107036190\n201007616\n201007687\n201010560\n202009020\n204004814\n204005617\n205005923\n205008145\n205009413\n205299309\n207004883\n207004900\n207007059\n207007370\n208005953\n212004409\n212004416\n212004984\n212007390\n214004323\n214006909\n214052221\n216007288\n216007658\n217006223\n219005747\n219005881\n219010384\n220023187\n220023532\n220025057\n221003112\n221005906\n222006349\n224011030\n224012330\n224012531\n224013045\n224950249\n224950256\n224951066\n224952006\n224953810\n224954638\n225008947\n227038023\n228004002\n228995233\n229008955\n229012503\n229013095\n229950531\n229950683\n229951260\n229951687\n229952521\n231005905\n231005944\n232006838\n232006860\n232006919\n232006965\n232008137\n232010136\n233004689\n233005058\n233007471\n233007707\n233007810\n234000768\n234002557\n234002564\n234005653\n234007883\n236012952\n236013353\n239000200\n239003995\n239005939\n239950555\n240002499\n240005997\n240006969\n242006611\n242009683\n242011964\n242013464\n244004465\n245000304\n245001770\n245003190\n245009145\n245012444\n245013173\n245014152\n245014219\n245014434\n245014579\n245015597\n245015830\n245015847\n245016914\n245017675\n245019295\n245020237\n245020501\n245021093\n245021343\n245021417\n245021456\n245023076\n245023245\n245024337\n245024369\n245024591\n245025482\n245025644\n245026246\n245027257\n245950521\n245952261\n245952720\n245953160\n245955270\n245956139\n245956629\n245956675\n245957580\n245957911\n245958457\n245958552\n245958898\n245961210\n245961474\n245965447\n245967028\n245967050\n248005540\n248006336\n248006505\n248007114\n248007700\n248008051\n248008622\n249005494\n249006650\n249007237\n249995322\n250005442\n250009060\n250011693\n250014006\n250015472\n250015680\n250016331\n250016620\n250146676\n250146813\n250146958\n250147013\n252000048\n253003637\n253006620\n253006927\n253007335\n253008699\n253009759\n253012374\n253013603\n253013650\n253017397\n253017982\n253018136\n253018263\n253018658\n253018739\n253019563\n253019637\n253019764\n253020431\n253020449\n254010884\n255006841\n255008687\n255010968\n255011312\n255013736\n255013870\n255014560\n255015010\n255017699\n255017882\n255017970\n255019015\n255019431\n255019470\n255021335\n255021367\n255995056\n256006322\n256012703\n256013231\n256015944\n256016190\n256019096\n256020373\n256020567\n256021017\n256022324\n256023046\n256023575\n256024233\n256024353\n256024843\n256996550\n256996711\n256997793\n257005650\n257006300\n257006614\n257006727\n257007128\n257007375\n257007840\n257008019\n257008315\n257009598\n257010508\n257010850\n257011332\n257011413\n257011822\n257011830\n258001489\n258008558\n258011568\n258014657\n258950053\n258950159\n258950631\n258951145\n258951339\n258951441\n258954474\n259006306\n259009339\n259012370\n259012500\n259013624\n259013649\n259014508\n260002433\n260003363\n260006195\n260007230\n260007914\n260008080\n260008604\n260011580\n261003045\n261010980\n261012794\n261013830\n261013974\n261016372\n261018073\n261018429\n261019486\n261020851\n261021380\n261021608\n261021742\n261022418\n261027092\n261032543\n261034283\n261036650\n261039806\n261065411\n261069769\n262000738\n262008945\n262010609\n262011024\n262013825\n262017756\n262025482\n262025570\n262025860\n262026285\n262030796\n263000025\n263005584\n263008289\n263009243\n263009885\n263010305\n263013994\n263015141\n263021120\n263021441\n263023897\n263024026\n263027323\n263027531\n263031070\n263032595\n264001751\n264003685\n264005146\n264008436\n264014479\n264017737\n264018508\n264020289\n264021275\n264022247\n264050082\n264051390\n264051777\n264052072\n264052788\n264053020\n264054954\n264055838\n264056292\n264057835\n264059409\n264059720\n264060154\n264060612\n264061430\n264061790\n264061905\n264062257\n264062666\n264062881\n264063081\n264063123\n264063719\n264064092\n264064751\n264064776\n264065314\n264065699\n264066290\n264066607\n264066702\n264066910\n264067696\n264067706\n264068026\n264069661\n264069982\n264070667\n264072463\n264072738\n264073072\n264073146\n264073386\n264073435\n264073717\n264074012\n264074125\n264074534\n264074799\n264076041\n264076309\n264076500\n264076556\n264080182\n265003159\n265004219\n265007932\n265014866\n265016398\n265018645\n265021380\n265023405\n265025160\n265025459\n265027914\n265029510\n265031251\n265031565\n265032657\n265033379\n265034037\n265034326\n265035190\n265035506\n265035545\n265036034\n265036725\n265037408\n265038384\n265039331\n265039356\n265040351\n265041394\n265045776\n265045906\n265046177\n265046635\n265047050\n265047283\n265048079\n265048382\n265048865\n265048921\n266002239\n266002905\n266005575\n266017323\n266017884\n266018172\n266023119\n266023736\n266025691\n266027441\n266027709\n266027770\n266028533\n266029079\n266029209\n266030540\n266031769\n266032956\n266032970\n266033491\n266033685\n266034150\n266035266\n266035594\n266035690\n266036703\n266040065\n266040234\n266040280\n266040548\n266043901\n266044310\n266045088\n266050352\n266051268\n266051959\n266053723\n266054371\n266057502\n266063320\n266073085\n266990028\n267013459\n267013804\n267015449\n267015657\n267016178\n267019436\n267020086\n267020858\n267022189\n267022485\n268000043\n268002001\n268002040\n268003887\n268008042\n268020089\n268020152\n268021614\n268027020\n268027750\n268028384\n268030094\n268031852\n268032479\n268032912\n268033514\n268033578\n268033994\n268034349\n268034613\n268035127\n268036956\n268037580\n268039019\n268040254\n268041829\n268043093\n268043209\n268043696\n268045485\n268047517\n268047796\n268050975\n268052690\n268054560\n268054786\n268055282\n268055412\n268056399\n268056776\n268058068\n268058075\n268058251\n268058808\n268059618\n268061141\n268061261\n268061511\n268061705\n268063276\n268063533\n268063702\n268063710\n268063830\n268063903\n268065918\n268066943\n268067697\n268067792\n268068980\n268068997\n268069574\n268070259\n268072633\n268072697\n268073154\n268074341\n268075024\n268075874\n268076116\n268078184\n268078963\n268079029\n268079251\n268079332\n268081229\n268082800\n268083353\n268083755\n268084156\n268086731\n268087943\n268094676\n268096730\n268098818\n268104130\n269008334\n269015243\n269015395\n269016504\n269020420\n269020839\n269020902\n269021511\n269022339\n269031291\n269031870\n269031887\n269033179\n269034253\n269034359\n269035698\n269035930\n269036490\n269037335\n269037776\n269038272\n269038427\n269038963\n269046114\n269996814\n269997984\n269998057\n269998410\n269999117\n270009290\n270018947\n270019443\n270020720\n270022541\n270405463\n270405978\n270406273\n270406435\n270406467\n270406570\n270406795\n270407118\n271005355\n271006430\n271008324\n271010570\n271055719\n272003015\n272009063\n272010453\n272012330\n272014137\n272014673\n272015620\n272016783\n272016825\n272019167\n272019350\n272019431\n272020677\n272021448\n272023533\n272024576\n272024671\n272024752\n272024858\n272900255\n272900576\n272900583\n272900618\n272900907\n272901019\n272901058\n272901379\n272901393\n272901523\n272901668\n272903658\n272903947\n272904605\n272904845\n272904926\n272905510\n272905528\n272905542\n272905550\n272906803\n272906850\n272907349\n272907540\n272907606\n272907980\n272908166\n272908462\n272909297\n272909392\n272909593\n272909730\n272910126\n272910687\n272911426\n272913381\n272914339\n272916248\n272918816\n272923164\n273001878\n273002381\n273005640\n273007598\n273016962\n273018230\n273019949\n273020461\n273021786\n273026657\n273027925\n273028534\n273032668\n273033196\n273037151\n273037352\n273038268\n273041239\n273041550\n273043821\n273045265\n273045603\n273047777\n273050716\n273051237\n273052470\n273052512\n273052953\n273053298\n273055993\n273056228\n273058271\n273059081\n273059116\n273059927\n273061041\n273061771\n273062849\n273064109\n273067999\n273068216\n273068657\n273068713\n273068738\n273069763\n273070335\n273070423\n273071360\n273071794\n273071970\n273072364\n273073505\n273073791\n273073819\n273074146\n273074530\n273075157\n273075277\n273077394\n273078599\n273078824\n273079539\n273079970\n273080975\n273081383\n273082309\n273082549\n273083422\n273084031\n273084465\n273084585\n273084592\n273086310\n273086977\n273087709\n273088205\n273088220\n273089255\n273089287\n273089390\n273090187\n273092593\n273092762\n273093734\n273093928\n273096020\n273098027\n273098563\n273098644\n273098820\n273098926\n273099253\n273099630\n273901195\n273901477\n273901822\n273902819\n273902865\n273903428\n273903724\n273907310\n273907327\n273909451\n273909596\n273910288\n273911203\n273911355\n273911482\n273912045\n273912214\n273912535\n273913874\n273913909\n273914268\n273914317\n273915293\n273915455\n273916339\n273916875\n273917780\n273917879\n273918030\n273918375\n273918907\n273918914\n273919763\n273920617\n273920952\n273921000\n273921829\n273923061\n273923128\n273923350\n273924315\n273924876\n273935941\n273937360\n273937787\n273941945\n273942498\n273943678\n273944223\n273952633\n273990100\n274002610\n274004208\n274016330\n274018377\n274019476\n274023088\n274029604\n274030720\n274031762\n274035573\n274036320\n274037500\n274042965\n274044850\n274047152\n274052635\n274056020\n274057665\n274062111\n274062859\n274062873\n274062954\n274063796\n274064045\n274065835\n274066645\n274066959\n274067293\n274067977\n274068716\n274068988\n274071557\n274072286\n274072430\n274072504\n274073071\n274078337\n274078930\n274079186\n274079299\n274079771\n274089610\n274089716\n274092236\n274092691\n274092807\n274095068\n274097146\n274097675\n274099665\n274101096\n274101770\n274103706\n274104548\n274107450\n274108180\n274108302\n274110502\n274110679\n274111908\n274111979\n274112041\n274113782\n274115885\n274117586\n274118445\n274118780\n274119079\n274119343\n274119625\n274120395\n274121134\n274122057\n274122875\n274122931\n274123815\n274124632\n274125308\n274126326\n274127760\n274128411\n274130467\n274131125\n274131559\n274131929\n274131950\n274132231\n274134790\n274135218\n274136211\n274136370\n274137430\n274137511\n274138628\n274139540\n274139607\n274140602\n274140850\n274141807\n274142053\n274143184\n274143297\n274143515\n274143667\n274144861\n274145181\n274145375\n274145424\n274146361\n274146925\n274147277\n274148224\n274148986\n274149228\n274150167\n274150953\n274151146\n274151611\n274151675\n274152125\n274152492\n274152622\n274152728\n274153802\n274154450\n274154468\n274155983\n274156585\n274156867\n274158790\n274158871\n274159219\n274159931\n274161715\n274161793\n274162772\n274163790\n274163938\n274164025\n274164106\n274164138\n274164508\n274165050\n274165452\n274166664\n274166946\n274167273\n274168238\n274168541\n274168661\n274170639\n274171657\n274171738\n274171840\n274171978\n274172347\n274172989\n274172996\n274174190\n274174714\n274174792\n274175637\n274175644\n274175838\n274177289\n274177546\n274177553\n274178980\n274179575\n274179590\n274180027\n274180845\n274181221\n274181486\n274181581\n274181630\n274183099\n274183162\n274183606\n274183807\n274183839\n274184529\n274184695\n274185321\n274186572\n274186861\n274187382\n274187784\n274187858\n274187914\n274187978\n274188964\n274189693\n274189735\n274190762\n274190949\n274192618\n274193280\n274390835\n274392857\n274900606\n274901053\n274901141\n274902265\n274902770\n274902850\n274903011\n274903452\n274904008\n274904150\n274904174\n274904463\n274904512\n274904840\n274906076\n274907224\n274907270\n274908210\n274908884\n274908972\n274910121\n274910611\n274911037\n274911291\n274911439\n274912190\n274912834\n274913281\n274913669\n274914038\n274914510\n274914670\n274914824\n274914849\n274916050\n274916211\n274916331\n274917102\n274917529\n274917800\n274918988\n274919340\n274919396\n274919974\n274920137\n274920730\n274920803\n274921437\n274921772\n274922310\n274923258\n274923850\n274923868\n274923900\n274924283\n274925015\n274925216\n274926153\n274926410\n274926770\n274927767\n274928344\n274929228\n274931435\n274931989\n274932478\n274933880\n274933947\n274934242\n274934387\n274934500\n274935221\n274935542\n274935736\n274936754\n274936916\n274937148\n274938977\n274939314\n274941105\n274941360\n274942476\n274943021\n274943159\n274943617\n274943864\n274946833\n274947322\n274948260\n274948284\n274948799\n274952499\n274953453\n274954520\n274955066\n274957137\n274958370\n274962190\n274962585\n274963733\n274964430\n274975591\n274982165\n274987050\n274990487\n274991804\n274991988\n274992607\n275003750\n275004722\n275008050\n275018010\n275020146\n275020330\n275020844\n275021213\n275021608\n275022094\n275022471\n275022785\n275022922\n275023098\n275024221\n275025088\n275026324\n275028628\n275033970\n275034276\n275035022\n275036876\n275037044\n275037100\n275037319\n275038496\n275040907\n275041202\n275047451\n275048543\n275049219\n275050278\n275051634\n275052807\n275053021\n275055702\n275055910\n275056512\n275056640\n275057393\n275059601\n275060565\n275060572\n275060999\n275062570\n275063809\n275064129\n275064619\n275066214\n275066373\n275066454\n275067190\n275069631\n275070034\n275070080\n275070203\n275070348\n275070490\n275070771\n275070806\n275071045\n275071060\n275071246\n275071327\n275072521\n275073652\n275073941\n275075794\n275076580\n275077738\n275078925\n275078957\n275079083\n275079661\n275079870\n275080434\n275080603\n275080723\n275081004\n275081156\n275081318\n275082223\n275082544\n275083097\n275084164\n275085489\n275086066\n275086122\n275086274\n275900969\n275901426\n275901497\n275902500\n275903529\n275904089\n275905460\n275905484\n275906801\n275906985\n275907234\n275908608\n275908742\n275908848\n275909908\n275910029\n275910050\n275910452\n275911079\n275911520\n275913100\n275913291\n275913622\n275914070\n275914231\n275914560\n275914760\n275914785\n275915838\n275916486\n275917673\n275919254\n275919913\n275922465\n275922578\n275924254\n275927495\n275929083\n275930184\n275990218\n276015678\n276022795\n276024383\n276024834\n276026214\n276027634\n276027659\n276027730\n276028003\n276029920\n276033363\n276039238\n276040473\n276040956\n276041639\n276042696\n276043467\n276046524\n276050810\n276051595\n276053000\n276053433\n276053440\n276054892\n276055737\n276060695\n276061770\n276062068\n276065541\n276068711\n276068849\n276072690\n276074031\n276074793\n276075557\n276075740\n276080300\n276082106\n276088690\n276090347\n276090570\n276092023\n276093010\n276094479\n276095049\n276095105\n276096973\n276097014\n276099702\n276100010\n276100563\n276101302\n276104286\n276105321\n276105593\n276105667\n276105917\n276106340\n276106565\n276106935\n276107463\n276110025\n276111438\n276112914\n276114686\n276115016\n276116394\n276116450\n276118070\n276118183\n276118560\n276119684\n276120055\n276121228\n276121517\n276121669\n276122119\n276122768\n276123024\n276124170\n276124363\n276124885\n276125159\n276127188\n276128030\n276128914\n276129604\n276129636\n276130529\n276130818\n276130945\n276131628\n276131770\n276132540\n276132621\n276132685\n276133382\n276133840\n276134499\n276135301\n276135358\n276135848\n276136601\n276136619\n276137556\n276138503\n276139345\n276140012\n276140661\n276140728\n276142161\n276142789\n276142813\n276143599\n276143694\n276144641\n276145370\n276145860\n276145885\n276146014\n276146864\n276147240\n276148300\n276148364\n276149079\n276149632\n276149840\n276150405\n276150420\n276151261\n276151350\n276151543\n276153614\n276154978\n276155040\n276155227\n276155322\n276156728\n276157369\n276157440\n276157930\n276158098\n276158147\n276158651\n276158683\n276159133\n276159158\n276159180\n276159366\n276159655\n276159817\n276160026\n276160160\n276160330\n276161679\n276162440\n276177929\n276901041\n276901330\n276902126\n276902380\n276902662\n276904290\n276904677\n276905166\n276906508\n276906995\n276907580\n276908030\n276908079\n276908343\n276908368\n276908505\n276908600\n276910102\n276910261\n276910575\n276911297\n276911385\n276911466\n276911730\n276912357\n276913671\n276914178\n276914724\n276915260\n276915870\n276916190\n276916714\n276917316\n276917475\n276917556\n276917595\n276918246\n276918398\n276918616\n276919264\n276919514\n276920076\n276920453\n276921810\n276922010\n276922027\n276922281\n276922637\n276922972\n276923020\n276923528\n276924218\n276924264\n276924352\n276924850\n276925003\n276925250\n276925268\n276925726\n276926582\n276926600\n276926889\n276927272\n276927353\n276927988\n276928163\n276928318\n276928396\n276928420\n276928445\n276928540\n276929343\n276930758\n276931134\n276931670\n276931705\n276932000\n276932353\n276932794\n276933100\n276933558\n276933886\n276934181\n276934424\n276935146\n276935178\n276935298\n276935450\n276935474\n276935844\n276936492\n276936598\n276936781\n276936862\n276936894\n276936904\n276937898\n276938235\n276938281\n276940347\n276943154\n276945200\n276947744\n276948018\n276949406\n276949893\n276952744\n276954413\n276954639\n276956925\n276957044\n276959644\n276961940\n276963591\n276964436\n276966352\n276967229\n276979351\n277004929\n277006179\n277012447\n277015293\n277016226\n277016392\n277018329\n277020776\n277023897\n277025397\n277031143\n277034507\n277034560\n277035500\n277035821\n277037152\n277039262\n277039544\n277039640\n277041328\n277041857\n277046541\n277047150\n277049045\n277050280\n277052792\n277052810\n277053027\n277053130\n277056130\n277058184\n277061998\n277062423\n277063113\n277065590\n277067012\n277067693\n277068658\n277068993\n277069281\n277069901\n277069919\n277071227\n277071467\n277071555\n277072661\n277073009\n277073714\n277075285\n277077028\n277077194\n277078416\n277079681\n277080461\n277081190\n277081377\n277081708\n277081786\n277084787\n277086872\n277088823\n277089249\n277089256\n277091689\n277094048\n277094665\n277094979\n277096447\n277099840\n277101390\n277101859\n277102066\n277103310\n277103782\n277104458\n277104715\n277104881\n277105719\n277105726\n277107314\n277108357\n277110204\n277110540\n277111649\n277112508\n277113082\n277113220\n277113639\n277113886\n277113903\n277114382\n277114390\n277114640\n277115450\n277116453\n277117520\n277118041\n277118570\n277118605\n277118980\n277119670\n277119729\n277120347\n277120690\n277121252\n277121679\n277122922\n277123933\n277124006\n277124119\n277124327\n277124782\n277125049\n277125271\n277125320\n277126684\n277126691\n277128096\n277128339\n277128755\n277129484\n277130641\n277130673\n277130842\n277132254\n277133515\n277133949\n277134075\n277134928\n277135336\n277136467\n277136795\n277137326\n277137647\n277137679\n277137816\n277138457\n277139034\n277140174\n277140657\n277140858\n277901460\n277901693\n277902658\n277902680\n277904729\n277906606\n277908106\n277909484\n277910948\n277911902\n277912688\n277912776\n277913554\n277913716\n277913900\n277914445\n277914533\n277915495\n277916315\n277916562\n277916629\n277916756\n277917943\n277918030\n277918390\n277919281\n277919595\n277920600\n277921072\n277922439\n277922559\n277923707\n277923760\n277923827\n277923880\n277924267\n277924316\n277924429\n277925630\n277925937\n277927469\n277927500\n277928007\n277930768\n277932187\n277932236\n277932405\n277932596\n277939591\n277941135\n277945651\n277946800\n277947240\n277947433\n277951623\n277952634\n277953758\n277955096\n277956798\n277956861\n277957424\n277967292\n277967454\n277967951\n277985414\n277985654\n278002498\n278002554\n278003886\n278005403\n278006083\n278007312\n278011929\n278012129\n278014912\n278017416\n278030985\n278034771\n278040648\n278044515\n278045163\n278045830\n278047435\n278048157\n278052467\n278054168\n278055147\n278058204\n278058282\n278059423\n278061574\n278062761\n278063050\n278064550\n278066967\n278067022\n278068241\n278068594\n278069100\n278069830\n278070770\

-------

In [71]:
df2020.filter(pl.col('ИНН поставщика')==2204075209)

shape: (0, 22)
┌─────────┬──────────┬─────────────┬────────────┬───┬────────────┬────────┬────────────┬───────────┐
│ Уровень ┆ Заказчик ┆ ИНН         ┆ Стоимость( ┆ … ┆ Форма      ┆ Тип    ┆ РНП сейчас ┆ РНП ранее │
│ ---     ┆ ---      ┆ заказчика   ┆ руб.)      ┆   ┆ публикации ┆ торгов ┆ ---        ┆ ---       │
│ i64     ┆ str      ┆ ---         ┆ Заказчик   ┆   ┆ ---        ┆ ---    ┆ i64        ┆ i64       │
│         ┆          ┆ i64         ┆ ---        ┆   ┆ str        ┆ str    ┆            ┆           │
│         ┆          ┆             ┆ f64        ┆   ┆            ┆        ┆            ┆           │
╞═════════╪══════════╪═════════════╪════════════╪═══╪════════════╪════════╪════════════╪═══════════╡
└─────────┴──────────┴─────────────┴────────────┴───┴────────────┴────────┴────────────┴───────────┘

In [72]:
df2015.filter(pl.col('ИНН поставщика')==2204075209)

shape: (5, 22)
┌─────────┬─────────────┬─────────────┬─────────────┬───┬────────────┬────────┬────────┬───────────┐
│ Уровень ┆ Заказчик    ┆ ИНН         ┆ Стоимость(р ┆ … ┆ Форма      ┆ Тип    ┆ РНП    ┆ РНП ранее │
│ ---     ┆ ---         ┆ заказчика   ┆ уб.)        ┆   ┆ публикации ┆ торгов ┆ сейчас ┆ ---       │
│ i64     ┆ str         ┆ ---         ┆ Заказчик    ┆   ┆ ---        ┆ ---    ┆ ---    ┆ i64       │
│         ┆             ┆ i64         ┆ ---         ┆   ┆ str        ┆ str    ┆ i64    ┆           │
│         ┆             ┆             ┆ f64         ┆   ┆            ┆        ┆        ┆           │
╞═════════╪═════════════╪═════════════╪═════════════╪═══╪════════════╪════════╪════════╪═══════════╡
│ 2       ┆ АО "БПО "СИ ┆ 2204056679  ┆ null        ┆ … ┆ Торговая   ┆ null   ┆ 0      ┆ 0         │
│         ┆ БПРИБОРМАШ" ┆             ┆             ┆   ┆ процедура  ┆        ┆        ┆           │
│ 2       ┆ АО "БПО "СИ ┆ 2204056679  ┆ null        ┆ … ┆ Торговая   ┆ null   ┆ 0      ┆ 0         │
│         ┆ БПРИБОРМАШ" ┆             ┆             ┆   ┆ процедура  ┆        ┆        ┆           │
│ 2       ┆ АО "БПО "СИ ┆ 2204056679  ┆ null        ┆ … ┆ Торговая   ┆ null   ┆ 0      ┆ 0         │
│         ┆ БПРИБОРМАШ" ┆             ┆             ┆   ┆ процедура  ┆        ┆        ┆           │
│ 2       ┆ МУП Г.      ┆ 2204000549  ┆ null        ┆ … ┆ Торговая   ┆ null   ┆ 0      ┆ 0         │
│         ┆ БИЙСКА      ┆             ┆             ┆   ┆ процедура  ┆        ┆        ┆           │
│         ┆ "ВОДОКАНАЛ" ┆             ┆             ┆   ┆            ┆        ┆        ┆           │
│ 2       ┆ АО "БПО "СИ ┆ 2204056679  ┆ null        ┆ … ┆ Торговая   ┆ null   ┆ 0      ┆ 0         │
│         ┆ БПРИБОРМАШ" ┆             ┆             ┆   ┆ процедура  ┆        ┆        ┆           │
└─────────┴─────────────┴─────────────┴─────────────┴───┴────────────┴────────┴────────┴───────────┘

In [ ]:
unrecognizible

399578230
618974292
706219302
771955477
802022689
806915148
909723206
1102076655
1102177570
1400314778
1402342900

6314045272
6317023348
6411014031
6449036286
6506322790
6612084498
6677010306
6832084927
7203032432

7710026754

9010226204
9011214064
26104580991
Код похож на ИНН физлица
26302900604
Код похож на ИНН физлица
27408960309
Код похож на ИНН физлица
31202713439
Код похож на ИНН физлица
55380036745
56204631818
Код похож на ИНН физлица
91700477969
Код похож на ИНН физлица
121525820000
Код похож на ИНН физлица
130805908830
Код похож на ИНН физлица
140200499787
Код похож на ИНН физлица
140200585958
Код похож на ИНН физлица
140202614139
Код похож на ИНН физлица
141001037536
141001042613
Код похож на ИНН физлица
141002456254
Код похож на ИНН физлица
141902303564
Код похож на ИНН физлица
142101447005
Код похож на ИНН физлица
142900044884
Код похож на ИНН физлица
143321397619
Код похож на ИНН физлица
143507107160
Код похож на ИНН физлица
165052332127
Код похож на ИНН физлица
170102796710
Код похож на ИНН физлица
177021710324
182902342881
Код похож на ИНН физлица
182907725503
Код похож на ИНН физлица
190300633075
Код похож на ИНН физлица
190302905408
Код похож на ИНН физлица
190305437691
Код похож на ИНН физлица
211077244275
Код похож на ИНН физлица
211669259752
Код похож на ИНН физлица
220415884203
Код похож на ИНН физлица
220417924250
Код похож на ИНН физлица
220418155840
Код похож на ИНН физлица
222330634720
Код похож на ИНН физлица
224500260901
Код похож на ИНН физлица
231489600648
Код похож на ИНН физлица
231500608296
231502360814
Код похож на ИНН физлица
231505341908
Код похож на ИНН физлица
232011589026
Код похож на ИНН физлица
233906240636
Код похож на ИНН физлица
235103572211
Код похож на ИНН физлица
244001359584
Код похож на ИНН физлица
245428308255
246304238705
Код похож на ИНН физлица
246315828978
Код похож на ИНН физлица
246317127304
Код похож на ИНН физлица
246506887614
Код похож на ИНН физлица
246524957720
Код похож на ИНН физлица
250362149859
Код похож на ИНН физлица
250362208448
Код похож на ИНН физлица
250397525698
251800812307
Код похож на ИНН физлица
251800911805
Код похож на ИНН физлица
252411487504
Код похож на ИНН физлица
253000512897
253001229572
Код похож на ИНН физлица
253604068332
Код похож на ИНН физлица
253614511480
Код похож на ИНН физлица
253696412215
Код похож на ИНН физлица
253696729357
Код похож на ИНН физлица
253697540883
Код похож на ИНН физлица
253707354504
Код похож на ИНН физлица
253713189560
Код похож на ИНН физлица
253804711409
Код похож на ИНН физлица
253805464512
Код похож на ИНН физлица
254002933920
Код похож на ИНН физлица
254007380980
Код похож на ИНН физлица
254301191057
Код похож на ИНН физлица
254305071610
Код похож на ИНН физлица
260602838795
Код похож на ИНН физлица
261810397166
Код похож на ИНН физлица
263400316417
Код похож на ИНН физлица
263400594213
Код похож на ИНН физлица
263504287418
Код похож на ИНН физлица
263506640580
Код похож на ИНН физлица
263507596703
Код похож на ИНН физлица
263603742196
270302155201
Код похож на ИНН физлица
270602308226
Код похож на ИНН физлица
270701023790
Код похож на ИНН физлица
272010689104
Код похож на ИНН физлица
272309101760
Код похож на ИНН физлица
272310640780
Код похож на ИНН физлица
280101590410
280118651483
Код похож на ИНН физлица
280701544100
Код похож на ИНН физлица
290102125049
290108530606
290125876646
Код похож на ИНН физлица
290127609043
Код похож на ИНН физлица
290136998043
Код похож на ИНН физлица
290218281088
Код похож на ИНН физлица
290219606740
Код похож на ИНН физлица
291401914051
301302384201
Код похож на ИНН физлица
311109934867
312700761538
Код похож на ИНН физлица
316600439241
330574351915
Код похож на ИНН физлица
332103158696
Код похож на ИНН физлица
332133529250
Код похож на ИНН физлица
333412722008
Код похож на ИНН физлица
340303858909
Код похож на ИНН физлица
340330567031
Код похож на ИНН физлица
340378573410
Код похож на ИНН физлица
342303870201
Код похож на ИНН физлица
344109934867
Код похож на ИНН физлица
344113722270
Код похож на ИНН физлица
344204410292
Код похож на ИНН физлица
344210382212
Код похож на ИНН физлица
344212336243
Код похож на ИНН физлица

------------

## Из спарка

In [130]:
df = pl.read_excel(source='spark_data/СПАРК-Список_data1.xlsx', 
                   read_options={'header_row':3}, 
                   schema_overrides={'Номер налогоплательщика':pl.Int64})
df.head(2)

shape: (2, 12)
┌────────────┬───────────┬───────────┬───────────┬───┬──────────┬──────────┬───────────┬───────────┐
│ Наименован ┆ Код регис ┆ Номер нал ┆ Код стати ┆ … ┆ Выручка  ┆ Персонал ┆ Сводный   ┆ Тип       │
│ ие/ФИО     ┆ трации    ┆ огоплател ┆ стики     ┆   ┆ ---      ┆ ---      ┆ риск      ┆ ---       │
│ ---        ┆ ---       ┆ ьщика     ┆ ---       ┆   ┆ i64      ┆ str      ┆ ---       ┆ str       │
│ str        ┆ str       ┆ ---       ┆ str       ┆   ┆          ┆          ┆ str       ┆           │
│            ┆           ┆ i64       ┆           ┆   ┆          ┆          ┆           ┆           │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪══════════╪═══════════╪═══════════╡
│ А И Г, ООО ┆ 117028007 ┆ 260011580 ┆ 20241409  ┆ … ┆ null     ┆ null     ┆ Недейству ┆ Юридическ │
│            ┆ 5470      ┆           ┆           ┆   ┆          ┆          ┆ ющий c    ┆ ое лицо   │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ 05.05.202 ┆           │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ 3         ┆           │
│ А СТРОЙ,   ┆ 115220400 ┆ 220407520 ┆ 32232864  ┆ … ┆ 87553000 ┆ 6        ┆ Низкий    ┆ Юридическ │
│ ООО        ┆ 2290      ┆ 9         ┆           ┆   ┆          ┆          ┆ риск      ┆ ое лицо   │
└────────────┴───────────┴───────────┴───────────┴───┴──────────┴──────────┴───────────┴───────────┘

In [131]:
for i in range(2, 9):
    new = pl.read_excel(source=f'spark_data/СПАРК-Список_data{i}.xlsx', 
                        read_options={'header_row':3}, 
                        schema_overrides={'Номер налогоплательщика':pl.Int64})
    df = pl.concat([df, new])

df.shape

(79924, 12)

In [132]:
nine = pl.read_excel(source=f'spark_data/СПАРК-Список_data9.xlsx', 
                        read_options={'header_row':3}, 
                        schema_overrides={'Номер налогоплательщика':pl.Int64})
df = pl.concat([df, new], how='diagonal')
df.head(1)

shape: (1, 12)
┌────────────┬────────────┬───────────┬───────────┬───┬─────────┬──────────┬───────────┬───────────┐
│ Наименован ┆ Код регист ┆ Номер нал ┆ Код стати ┆ … ┆ Выручка ┆ Персонал ┆ Сводный   ┆ Тип       │
│ ие/ФИО     ┆ рации      ┆ огоплател ┆ стики     ┆   ┆ ---     ┆ ---      ┆ риск      ┆ ---       │
│ ---        ┆ ---        ┆ ьщика     ┆ ---       ┆   ┆ i64     ┆ str      ┆ ---       ┆ str       │
│ str        ┆ str        ┆ ---       ┆ str       ┆   ┆         ┆          ┆ str       ┆           │
│            ┆            ┆ i64       ┆           ┆   ┆         ┆          ┆           ┆           │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═════════╪══════════╪═══════════╪═══════════╡
│ А И Г, ООО ┆ 1170280075 ┆ 260011580 ┆ 20241409  ┆ … ┆ null    ┆ null     ┆ Недейству ┆ Юридическ │
│            ┆ 470        ┆           ┆           ┆   ┆         ┆          ┆ ющий c    ┆ ое лицо   │
│            ┆            ┆           ┆           ┆   ┆         ┆          ┆ 05.05.202 ┆           │
│            ┆            ┆           ┆           ┆   ┆         ┆          ┆ 3         ┆           │
└────────────┴────────────┴───────────┴───────────┴───┴─────────┴──────────┴───────────┴───────────┘

In [133]:
df = df.select(['Номер налогоплательщика', 'Выручка', 'Сводный риск'])
df = df.with_columns(pl.when(pl.col('Сводный риск').str.contains('Недействующий')).then(pl.lit('Недействующий')).otherwise(pl.col('Сводный риск')).alias('Сводный риск'))
df.head(15)

shape: (15, 3)
┌─────────────────────────┬───────────┬───────────────────┐
│ Номер налогоплательщика ┆ Выручка   ┆ Сводный риск      │
│ ---                     ┆ ---       ┆ ---               │
│ i64                     ┆ i64       ┆ str               │
╞═════════════════════════╪═══════════╪═══════════════════╡
│ 260011580               ┆ null      ┆ Недействующий     │
│ 2204075209              ┆ 87553000  ┆ Низкий риск       │
│ 2221121656              ┆ 6935000   ┆ Низкий риск       │
│ 275913100               ┆ 329215000 ┆ Низкий риск       │
│ 1656049604              ┆ 4457000   ┆ Низкий риск       │
│ …                       ┆ …         ┆ …                 │
│ 1909020077              ┆ null      ┆ Риск не определен │
│ 1659002844              ┆ null      ┆ Недействующий     │
│ 1655040278              ┆ 119975000 ┆ Низкий риск       │
│ 1215178211              ┆ 3481000   ┆ Высокий риск      │
│ 1900000252              ┆ null      ┆ Низкий риск       │
└─────────────────────────┴───────────┴───────────────────┘

In [134]:
df = df.filter(pl.col('Номер налогоплательщика').is_not_null())
print(df.shape)
df.select(pl.all().null_count())

(89896, 3)

shape: (1, 3)
┌─────────────────────────┬─────────┬──────────────┐
│ Номер налогоплательщика ┆ Выручка ┆ Сводный риск │
│ ---                     ┆ ---     ┆ ---          │
│ u32                     ┆ u32     ┆ u32          │
╞═════════════════════════╪═════════╪══════════════╡
│ 0                       ┆ 29662   ┆ 242          │
└─────────────────────────┴─────────┴──────────────┘

In [135]:
df = df.rename({'Номер налогоплательщика':'ИНН поставщика'})

In [136]:
df = df.unique()
df.shape

(79912, 3)

------

## Соединяем

In [140]:
df2015.shape

(209451, 22)

In [148]:
df2020_rev = df2020.join(other=df, on='ИНН поставщика', how='left')
df2015_rev = df2015.join(other=df, on='ИНН поставщика', how='left')

In [149]:
df2020_rev.null_count()

shape: (1, 24)
┌─────────┬──────────┬──────────────┬─────────────┬───┬────────────┬───────────┬─────────┬─────────┐
│ Уровень ┆ Заказчик ┆ ИНН          ┆ Стоимость(р ┆ … ┆ РНП сейчас ┆ РНП ранее ┆ Выручка ┆ Сводный │
│ ---     ┆ ---      ┆ заказчика    ┆ уб.)        ┆   ┆ ---        ┆ ---       ┆ ---     ┆ риск    │
│ u32     ┆ u32      ┆ ---          ┆ Заказчик    ┆   ┆ u32        ┆ u32       ┆ u32     ┆ ---     │
│         ┆          ┆ u32          ┆ ---         ┆   ┆            ┆           ┆         ┆ u32     │
│         ┆          ┆              ┆ u32         ┆   ┆            ┆           ┆         ┆         │
╞═════════╪══════════╪══════════════╪═════════════╪═══╪════════════╪═══════════╪═════════╪═════════╡
│ 0       ┆ 0        ┆ 0            ┆ 36823       ┆ … ┆ 0          ┆ 0         ┆ 35463   ┆ 10834   │
└─────────┴──────────┴──────────────┴─────────────┴───┴────────────┴───────────┴─────────┴─────────┘

In [150]:
df2015_rev.null_count()

shape: (1, 24)
┌─────────┬──────────┬──────────────┬─────────────┬───┬────────────┬───────────┬─────────┬─────────┐
│ Уровень ┆ Заказчик ┆ ИНН          ┆ Стоимость(р ┆ … ┆ РНП сейчас ┆ РНП ранее ┆ Выручка ┆ Сводный │
│ ---     ┆ ---      ┆ заказчика    ┆ уб.)        ┆   ┆ ---        ┆ ---       ┆ ---     ┆ риск    │
│ u32     ┆ u32      ┆ ---          ┆ Заказчик    ┆   ┆ u32        ┆ u32       ┆ u32     ┆ ---     │
│         ┆          ┆ u32          ┆ ---         ┆   ┆            ┆           ┆         ┆ u32     │
│         ┆          ┆              ┆ u32         ┆   ┆            ┆           ┆         ┆         │
╞═════════╪══════════╪══════════════╪═════════════╪═══╪════════════╪═══════════╪═════════╪═════════╡
│ 0       ┆ 0        ┆ 0            ┆ 178647      ┆ … ┆ 0          ┆ 0         ┆ 67381   ┆ 11675   │
└─────────┴──────────┴──────────────┴─────────────┴───┴────────────┴───────────┴─────────┴─────────┘

Сохраним данные без заполнения null

In [154]:
df2015_rev.write_excel( dtype_formats={pl.Date: "yyyy-mm-dd"})

Теперь заполним null

In [155]:
df2020_rev = df2020_rev.with_columns(pl.col('Выручка').fill_null(0), pl.col('Сводный риск').fill_null('Риск не определен'))
df2015_rev = df2015_rev.with_columns(pl.col('Выручка').fill_null(0), pl.col('Сводный риск').fill_null('Риск не определен'))

In [156]:
df2020_rev.null_count()

shape: (1, 24)
┌─────────┬──────────┬──────────────┬─────────────┬───┬────────────┬───────────┬─────────┬─────────┐
│ Уровень ┆ Заказчик ┆ ИНН          ┆ Стоимость(р ┆ … ┆ РНП сейчас ┆ РНП ранее ┆ Выручка ┆ Сводный │
│ ---     ┆ ---      ┆ заказчика    ┆ уб.)        ┆   ┆ ---        ┆ ---       ┆ ---     ┆ риск    │
│ u32     ┆ u32      ┆ ---          ┆ Заказчик    ┆   ┆ u32        ┆ u32       ┆ u32     ┆ ---     │
│         ┆          ┆ u32          ┆ ---         ┆   ┆            ┆           ┆         ┆ u32     │
│         ┆          ┆              ┆ u32         ┆   ┆            ┆           ┆         ┆         │
╞═════════╪══════════╪══════════════╪═════════════╪═══╪════════════╪═══════════╪═════════╪═════════╡
│ 0       ┆ 0        ┆ 0            ┆ 36823       ┆ … ┆ 0          ┆ 0         ┆ 0       ┆ 0       │
└─────────┴──────────┴──────────────┴─────────────┴───┴────────────┴───────────┴─────────┴─────────┘

In [159]:
df2015_rev.write_excel( dtype_formats={pl.Date: "yyyy-mm-dd"})